---
abstract: 'Median finding algorithm'
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  ExtUtils::CBuilder: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4229, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Algorithm-MedianSelect-XS
provides:
  Algorithm::MedianSelect::XS:
    file: lib/Algorithm/MedianSelect/XS.pm
    version: 0.21_01
requires:
  Carp: '0'
  Exporter: '0'
  XSLoader: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/stsc/Algorithm-MedianSelect-XS
version: 0.21_01
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
